# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs tests
    - name: Test
      run: .\build\test.ps1

    # Runs the publish script that builds and creates release artifacts
    - name: Build and create release artifacts
      run: .\build\publish.ps1
    
    # Uploads release artifact for net48
    - name: Upload .NET Framework 4.8 release artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact-net48
        path: publish\RadeonSoftwareSlimmer_*_net48.zip

    # Uploads release artifact for netcoreapp31
    - name: Upload .NET Core 3.1 release artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact-netcoreapp31
        path: publish\RadeonSoftwareSlimmer_*_netcoreapp31.zip