name: Continuous-Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: 
      - master

jobs:
  build:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    # https://github.com/actions/runner-images
    # https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
    runs-on: windows-2022
    steps:

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # https://github.com/marketplace/actions/gittools
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v2
      with:
        versionSpec: '5.x'
        preferLatestVersion: true

    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v2

    - name: Test
      run: .\build\test.ps1

    - name: Publish
      run: .\build\publish.ps1
