name: Code Change

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: 
      - master
    types: [opened, reopened, synchronize]

jobs:
  GitVersion:
    name: Get Version
    uses: ./.github/workflows/reuse-gitversion.yml

  CI:
    name: Continuous Integration
    needs: GitVersion
    uses: ./.github/workflows/reuse-ci.yml
    with:
      build-version: ${{ needs.GitVersion.outputs.FullSemVer }}
      archive-publish: false
