name: Code Change

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: 
      - master
    types: [opened, reopened, synchronize]

jobs:
  GitVersion:
    name: Get Version
    uses: ./.github/workflows/reuse-gitversion.yml

  CI:
    name: Continuous Integration
    needs: GitVersion
    runs-on: windows-latest
    env:
      BUILD_VERSION: ${{ needs.GitVersion.outputs.FullSemVer }}
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE: true
      DOTNET_NOLOGO: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: ./build/build.ps1 

    - name: Test
      run: ./build/test.ps1

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./artifacts/tests/*.trx
        if-no-files-found: warn

    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        artifact: test-results
        name: Test Results
        path: '*.trx'
        reporter: dotnet-trx
        only-summary: false
        fail-on-error: true
        fail-on-empty: true

    - name: Publish
      run: ./build/publish.ps1
