name: Release

on:
  push:
    tags:
      - '[1-9].[0-9]+.[0-9]+'

jobs:
  build:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    # https://github.com/actions/runner-images
    # https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
    runs-on: windows-2022
    steps:

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # https://github.com/marketplace/actions/gittools
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3
      with:
        versionSpec: '6.0.x'
        preferLatestVersion: true

    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v3

    - name: Test
      run: .\build\test.ps1

    - name: Publish
      run: .\build\publish.ps1

      # https://github.com/marketplace/actions/create-release
      # git tag 1.2.3
      # git push --tags
    - name: Create Release
      # You may pin to the exact commit or the version.
      # uses: ncipollo/release-action@4c75f0f2e4ae5f3c807cf0904605408e319dcaac
      uses: ncipollo/release-action@v1
      with:
        # An optional flag which indicates if artifact read or upload errors should fail the build.
        artifactErrorsFailBuild: true
        # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
        artifacts: "publish/RadeonSoftwareSlimmer_*_net*.zip"
        # The content type of the artifact. Defaults to raw
        artifactContentType: "application/zip"
        # An optional body file for the release. This should be the path to the file
        bodyFile: "build/release-notes-template.md"
        # Optionally marks this release as a draft release. Set to true to enable.
        draft: true
        # Indicates if release notes should be automatically generated.
        generateReleaseNotes: false
        # An optional name for the release. If this is omitted the tag will be used.
        name: "Radeon Software Slimmer ${{ steps.gitversion.outputs.semVer }}"
        # Indicates if the release body should be omitted.
        prerelease: false
        # The Github token.
        token: ${{ secrets.GITHUB_TOKEN }}
