name: Continuous Integration

on:
  workflow_call:
    inputs:
      build-version:
        description: 'The version to build'
        default: 1.0.0
        required: true
        type: string
      archive-publish:
        description: 'Archive the published build artifact for releasing'
        default: false
        required: false
        type: boolean

jobs:
  build-test-publish:
    name: Build Test Publish
    needs: GitVersion
    runs-on: windows-latest
    env:
      BUILD_VERSION: ${{ inputs.build-version }}
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE: true
      DOTNET_NOLOGO: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: ./build/build.ps1 

    - name: Test
      run: ./build/test.ps1

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./artifacts/tests/*.trx
        if-no-files-found: warn

    - name: Publish Test Results
      if: success() || failure()
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Test Results
        path: '*.trx'
        reporter: dotnet-trx
        only-summary: false
        fail-on-error: true
        fail-on-empty: true

    - name: Publish
      run: ./build/publish.ps1

    - name: Upload Published Archives
      if: ${{ inputs.archive-publish == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: published-archives
        path: ./artifacts/publish/RadeonSoftwareSlimmer_*_net*.zip
        if-no-files-found: error
        compression-level: 0
